
# ... To get rid of class property (static...) error
#   https://github.com/airbnb/javascript/issues/589
parser: 'babel-eslint'

# extends: 'react-app'
extends: 'airbnb'

env:
  browser: true

rules:
  react/jsx-filename-extension:
    - off
  comma-dangle:
    - off
  react/destructuring-assignment:
    - off
  no-console:
    - off
  react/jsx-fragments:
    - off
  object-property-newline:
    - off
